Repository RedRiotTank/PGPI-p9, pull requests merged in 2024-12, with the labels that each got.

#2 Update tarea-n1-imp
  tarea-n1-imp
Labels: bug

#1 Update tarea-n2-imp
  tarea-n2-imp
Labels: documentation

#5 Merge develop to main
  tarea-n1-imp
  tarea-n1-imp-2
  tarea-n2-imp
  tarea-n2-imp-2
Labels: enhancement
